version: '3.7'
services:
  mongo:    
    container_name: stably-mongodb
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_DATABASE: stably-test
  nodejs:
    container_name: stably-nodejs-api
    build:
      context: .
      dockerfile: ./docker/nodejs.dockerfile
    restart: on-failure
    volumes:
      - .:/api
    environment: 
      - "NODE_ENV=development"
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
  nginx:
    container_name: stably-nginx-reverse-proxy
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - nodejs
    restart: on-failure
    network_mode: "host"
  redis:
    container_name: stably-redis-cache-queue
    command: ["redis-server", "--appendonly", "yes"]
    build:
      context: .
      dockerfile: ./docker/redis.dockerfile
    ports:
      - 6379:6379
    networks:
      - backend

volumes: 
  .:
