version: '3.7'
services:
  mongo:    
    container_name: stably-mongodb
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_DATABASE: stably-test
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: on-failure
    ports:
      - 8082:8081
    links:
      - mongo
  nodejs:
    container_name: stably-nodejs-api
    build:
      context: .
      dockerfile: nodejs.dockerfile
    restart: on-failure
    volumes:
      - .:/api
    environment: 
      - "NODE_ENV=development"
    ports:
      - "3000:3000"
    links:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]

volumes: 
  .: